spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javavenkats5/microservices-config
          username: youremail@gmail.com
          password: yourpassword
          clone-on-start: true
          timeout: 30
          default-label: master
          
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/